require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
-- require "user.project"
-- require "user.alpha"
require "user.whichkey"
require "user.neogit"
require "user.comment"
require "user.autopairs"
require "user.impatient"
require "user.dial"
require "user.go"
require "user.worktree"
-- require "user.debug"
require "user.dadbod"

