return {
	settings = {
		gopls = {
			codelenses = {
				gc_details = false,
				generate = true,
				regenerate_cgo = true,
				run_govulncheck = true,
				test = true,
				tidy = true,
				upgrade_dependency = true,
				vendor = true,
			},
			hints = {
				assignVariableTypes = false,
				compositeLiteralFields = true,
				compositeLiteralTypes = true,
				constantValues = true,
				functionTypeParameters = true,
				parameterNames = true,
				rangeVariableTypes = true,
			},
			usePlaceholders = false,
			staticcheck = false,
			semanticTokens = true,
			-- buildFlags = { "-tags=linux,windows" },
			-- buildFlags = { "-tags=linux" },
			-- buildFlags = { "-tags=windows,!linux" },
			completeUnimported = true,
			analyses = {
				fieldalignment = false,
				nilness = true,
				unusedparams = false,
				unusedwrite = false,
				useany = false,
			},
			directoryFilters = { "-.git", "-.vscode", "-.idea", "-.vscode-test", "-node_modules" },
		},
	},
}
