vim.cmd.colorscheme("seoulbones")

vim.api.nvim_set_hl(0, "TreesitterContext", { bg ="#4B4B4B" })
vim.api.nvim_set_hl(0, "IlluminatedWordText", { bg="#4B4B4B"})
vim.api.nvim_set_hl(0, "IlluminatedWordRead", { bg = "#4B4B4B"})
vim.api.nvim_set_hl(0, "IlluminatedWordWrite", { bg = "#4B4B4B" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#353535" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#353535" })
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
